import type { OverviewSectionLabels } from "@/components/features/research/OverviewSection";

export const overviewSectionTestLabels: OverviewSectionLabels = {
  briefTitle: "Research Brief",
  keyResultsTitle: "Key Results",
  guidedWorkflowTitle: "Guided workflow",
  conclusionTitle: "Research Conclusion",
  evidencePreviewTitle: "Evidence preview",
  brief: {
    owner: "Owner",
    updated: "Updated",
    evidenceStatus: "Evidence",
    decisionStatus: "Evaluation status",
    evidenceComplete: "Evidence complete",
    evidenceIncomplete: "Incomplete",
    evidencePending: "Not started",
    decisionPending: "Decision pending evidence and review.",
    evaluationCompleted: "Completed",
    evaluationIncomplete: "Incomplete",
    evaluationBlocked: "Blocked",
  },
  keyResults: {
    strategyTotalReturn: "Strategy total return",
    benchmarkTotalReturn: "Benchmark total return",
    maxDrawdown: "Maximum drawdown",
    oosSharpe: "Out-of-sample Sharpe ratio",
    unavailable: "Run the research to calculate historical evidence.",
    oosSharpeUnavailable: "Run validation to calculate out-of-sample Sharpe ratio.",
  },
  guidedFlow: {
    title: "Guided workflow",
    stepRunResearch: "Run Research",
    stepValidateEvidence: "Validate evidence",
    stepReviewEvaluation: "Review evaluation",
    stepAskCopilot: "Ask Copilot",
    unavailableAfterExecution: "Complete historical execution first.",
    unavailableAfterValidation: "Run validation before requesting evaluation.",
    unavailableAfterEvaluation: "Request evaluation before asking Copilot.",
    loading: "In progress…",
    failed: "Needs attention",
  },
  nextStep: {
    title: "Next step",
    runResearchTitle: "Run Research",
    runResearchDescription: "Calculate historical evidence using the configured protocol.",
    runResearchCta: "Run Research",
    runResearchLoadingCta: "Running research…",
    runResearchRetryCta: "Retry research",
    validateTitle: "Validate Evidence",
    validateDescription: "Run deterministic checks.",
    validateCta: "Run Validation",
    evaluateTitle: "Review Evaluation",
    evaluateDescription: "Summarize evidence coverage.",
    evaluateCta: "Request Evaluation",
    copilotTitle: "Ask Copilot",
    copilotDescription: "Ask questions grounded in evidence.",
    copilotCta: "Open Copilot",
  },
  conclusion: {
    title: "Research Conclusion",
    notRequested: "Evaluation has not been requested.",
    incomplete: "Current evidence does not support a final research decision.",
    blocked: "Evaluation is blocked by required evidence.",
    completed: "Completed",
    coverageLabel: "Coverage",
    keyStrengthsLabel: "Key strengths",
    limitationLabel: "Known weaknesses",
    nextActionLabel: "Next actions",
  },
};
