import type { OverviewSectionLabels } from "@/components/features/research/OverviewSection";

export const overviewSectionTestLabels: OverviewSectionLabels = {
  keyResultsTitle: "Key Results",
  conclusionTitle: "Research Conclusion",
  evidencePreviewTitle: "Validation preview",
  primaryActionCaption: "Continue",
  validationCaption: "Validation",
  decisionCaption: "Decision",
  supportCaption: "Provenance",
  validationStatus: "Validation",
  decisionStatus: "Decision status",
  validationComplete: "Validation complete",
  validationIncomplete: "Incomplete",
  validationPending: "Not started",
  decisionPending: "Decision pending validation.",
  evaluationCompleted: "Completed",
  evaluationIncomplete: "Incomplete",
  evaluationBlocked: "Blocked",
  keyResults: {
    strategyTotalReturn: "Strategy total return",
    benchmarkTotalReturn: "Benchmark total return",
    maxDrawdown: "Maximum drawdown",
    oosSharpe: "Out-of-sample Sharpe ratio",
    unavailable: "Run the research to calculate historical evidence.",
    unavailableTitle: "Key results not available yet",
    oosSharpeUnavailable: "Run validation to calculate out-of-sample Sharpe ratio.",
  },
  nextStep: {
    title: "Next step",
    runResearchTitle: "Run Research",
    runResearchDescription: "Calculate historical evidence using the configured protocol.",
    runResearchCta: "Run Research",
    runResearchLoadingCta: "Running research…",
    runResearchRetryCta: "Retry research",
    validateTitle: "Run Validation",
    validateDescription: "Run deterministic checks.",
    validateCta: "Run Validation",
    openExperimentTitle: "Open Experiment",
    openExperimentDescription: "Review experiments for this research.",
    openExperimentCta: "Open Experiment",
    openRobustnessTitle: "Open Robustness",
    openRobustnessDescription: "Organise robustness work after Validation.",
    openRobustnessCta: "Open Robustness",
    openPaperTitle: "Open Paper Trading",
    openPaperDescription: "Review research deployment and observation staging.",
    openPaperCta: "Open Paper Trading",
    openDecisionTitle: "Open Decision",
    openDecisionDescription: "Review approval staging for this research.",
    openDecisionCta: "Open Decision",
    openArchiveTitle: "Open Archive",
    openArchiveDescription: "Close out this research thread when ready.",
    openArchiveCta: "Open Archive",
  },
  conclusion: {
    title: "Research Conclusion",
    notRequested: "Validation summary has not been requested.",
    incomplete: "Current evidence does not support a final research decision.",
    blocked: "Decision is blocked by required validation evidence.",
    completed: "Completed",
    coverageLabel: "Coverage",
    keyStrengthsLabel: "Key strengths",
    limitationLabel: "Known weaknesses",
    nextActionLabel: "Next actions",
  },
};
